baseURL = "https://zeroasterisk.com"
languageCode = "en-us"
title = "Alan Blount & Family | zeroasterisk"

paginate = 5 # Number of posts to show before paginating
theme = "bulma" # to use as default theme

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "UA-2011466-1"
disqusShortname = "zeroasterisk"
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

canonifyURLs = true
[permalinks]
  post = "/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  theme_variant = "flatly"
# ^^^ possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description = "alan's personal blog and website: family, friends, whatever"
  powered_by = "hugo" # Optional, controls name display on footer
  hide_author = false # Optional, set true to hide author name on posts
  images = [
    "https://en.gravatar.com/userimage/831761/080d157cba7201fa2d89172617f6b7bb.jpg?size=200",
    "https://en.gravatar.com/userimage/831761/521a5488e0ab6a4eb70d9f3ac295787a.png?size=200",
    "https://en.gravatar.com/userimage/831761/52e86082cb40348a6f97484cf2983f94.png?size=200",
    "https://en.gravatar.com/userimage/831761/5c27690cae3cb625e32ef3cad3319a42.jpg?size=200"
  ]
  github = "zeroasterisk" # Optional, to display link to github account in menu bar
  twitter = "zeroasterisk" # Optional, to display link to twitter account in menu bar
